import random

quiz_data = {
    "The blood libel charge falsely accuses Jews of...?": ["All of them", "Israelis eating Palestinian children, harvesting their organs, and/or drinking their blood", "Using blood as an ingredient in ritual breads", "Kidnapping and killing Christian children for their blood"],
    "Associating Jews with greed can be found in": ["All of them", "Conspiracy theories about the Rothschilds", "Nazi propaganda", "Shakespeare's The Merchant of Venice"],
    "Hamas terrorists and pro-Palestinian activists have popularized this phrase that calls for the erasing of the State of Israel and its people…": ['"From the River to the Sea"', '"Jews Will Not Replace Us"', '"Not the Real Jews"', '"Zionism is Racism"'],
    "Likening the Gaza Strip to the Warsaw Ghetto is a form of this antisemitic trope or term:": ["Holocaust distortion", "Zionist Occupied Government (ZOG)", "Deadly exchange", "Blood Libel"],
    "This claim suggests that Jews run Hollywood, accusing them of using their influence in order to gain control…": ["Jewish agents", "Poisoning the well", "Globalist", "Jewish figures"],
    "The Protocols of the Elders of Zion is a notorious antisemitic hoax claiming...?": ["Jews conspire to control the world", "Jews are responsible for societal ills", "Jews seek global domination", "All of the above"],
    "Which historical event resulted in the mass murder of six million Jews by the Nazi regime?": ["The Holocaust", "The Final Solution", "Kristallnacht", "The Nuremberg Laws"],
    "What is the term for the systematic discrimination, prejudice, or hostility directed against Jews?": ["Antisemitism", "Racism", "Xenophobia", "Islamophobia"],
    "Which medieval event led to the widespread accusation that Jews were responsible for spreading the Black Death?": ["The Black Death pandemic", "The Crusades", "The Spanish Inquisition", "The Reconquista"],
    "Which conspiracy theory falsely claims that Jews were behind the 9/11 terrorist attacks?": ["9/11 conspiracy theories", "The Mossad theory", "The Dancing Israelis theory", "The Controlled Demolition theory"],
    "Which Russian term refers to violence against Jews, particularly pogroms in Imperial Russia?": ["Pogrom", "Kishinev massacre", "Pale of Settlement", "The Dreyfus Affair"],
    "Which country was responsible for the Dreyfus Affair, a notable instance of antisemitism in the late 19th and early 20th centuries?": ["France", "Germany", "Russia", "Austria-Hungary"],
    "What was the Einsatzgruppen's role during World War II in perpetrating the Holocaust?": ["Mobile killing units", "Concentration camp guards", "Nazi propaganda", "Nazi youth indoctrination"],
    "Which term refers to the belief that Jews are collectively responsible for wrongdoing or misfortune?": ["Collective guilt", "Jewish guilt", "Original sin", "Scapegoating"],
    "Which English monarch expelled Jews from England in 1290, leading to centuries of Jewish absence from the country?": ["Edward I", "Henry VIII", "Elizabeth I", "Richard the Lionheart"],
    "What was the purpose of the Nuremberg Laws enacted by Nazi Germany in 1935?": ["Legalized discrimination against Jews", "Forced Jews to wear identifying badges", "Established racial purity", "All of the above"],
    "Which antisemitic publication published in Nazi Germany promoted hatred against Jews and supported Hitler's regime?": ["Der Stürmer", "Mein Kampf", "The Protocols of the Elders of Zion", "The International Jew"],
    "Which organization was responsible for the bombing of the AMIA Jewish community center in Buenos Aires in 1994?": ["Hezbollah", "Al-Qaeda", "Islamic Jihad Organization", "Iranian Revolutionary Guard Corps"],
    "What is the term for the systematic effort by Nazi Germany to annihilate European Jews during World War II?": ["The Final Solution", "The Holocaust", "The Kristallnacht", "The Nuremberg Laws"],
    "Which medieval monarch ordered the expulsion of Jews from Spain in 1492?": ["Ferdinand II of Aragon", "Isabella I of Castile", "Alfonso X of Castile", "Philip II of Spain"]
}

quiz_answers = {"The blood libel charge falsely accuses Jews of...?": "All of them",
                "Associating Jews with greed can be found in": "All of them",
                "Hamas terrorists and pro-Palestinian activists have popularized this phrase that calls for the erasing of the State of Israel and its people…": '"From the River to the Sea"',
                "Likening the Gaza Strip to the Warsaw Ghetto is a form of this antisemitic trope or term:": "Holocaust distortion",
                "This claim suggests that Jews run Hollywood, accusing them of using their influence in order to gain control…": "Jewish agents",
                "The Protocols of the Elders of Zion is a notorious antisemitic hoax claiming...?": "All of the above",
                "Which historical event resulted in the mass murder of six million Jews by the Nazi regime?": "The Holocaust",
                "What is the term for the systematic discrimination, prejudice, or hostility directed against Jews?": "Antisemitism",
                "Which medieval event led to the widespread accusation that Jews were responsible for spreading the Black Death?": "The Black Death pandemic",
                "Which conspiracy theory falsely claims that Jews were behind the 9/11 terrorist attacks?": "The Mossad theory",
                "Which Russian term refers to violence against Jews, particularly pogroms in Imperial Russia?": "Pogrom",
                "Which country was responsible for the Dreyfus Affair, a notable instance of antisemitism in the late 19th and early 20th centuries?": "France",
                "What was the Einsatzgruppen's role during World War II in perpetrating the Holocaust?": "Mobile killing units",
                "Which term refers to the belief that Jews are collectively responsible for wrongdoing or misfortune?": "Collective guilt",
                "Which English monarch expelled Jews from England in 1290, leading to centuries of Jewish absence from the country?": "Edward I",
                "What was the purpose of the Nuremberg Laws enacted by Nazi Germany in 1935?": "All of the above",
                "Which antisemitic publication published in Nazi Germany promoted hatred against Jews and supported Hitler's regime?": "Der Stürmer",
                "Which organization was responsible for the bombing of the AMIA Jewish community center in Buenos Aires in 1994?": "Hezbollah",
                "What is the term for the systematic effort by Nazi Germany to annihilate European Jews during World War II?": "The Final Solution",
                "Which medieval monarch ordered the expulsion of Jews from Spain in 1492?": "Ferdinand II of Aragon"
                }